# Generated by Django 4.1.7 on 2023-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onirix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
